import color from "color";
import DefaultTheme from "@styles/defaultTheme";
import {
  black,
  white,
  pinkA100,
  matterhorn,
  grey76,
  grey7,
  linkBlue,
  headerGrey,
  grey50,
  nightRider,
  darkmodewhite,
  darkmodeBlueText,
} from "@styles/colors";

const DarkTheme = {
  ...DefaultTheme,
  dark: true,
  mode: "adaptive",
  colors: {
    ...DefaultTheme.colors,
    primary: "#0090F0",
    accent: "#919191",
    background: grey7,
    surface: "#303030",
    error: "#ff6e6e",
    onBackground: white,
    backButton: "#FAFAFA",
    hyperLinks: linkBlue,
    hyperLinkStyle: "none",
    onSurface: white,
    loader: white,
    adBox: black,
    text: white,
    secondaryText: grey76,
    whiteText: white,
    sectionArticle: grey76,
    line: white,
    lightBackground: grey7,
    publishedDate: white,
    cardBg: matterhorn,
    articleTimeStamp: grey76,
    navNormal: white,
    navFocused: white,
    sectionTitle: white,
    disabled: color(white).alpha(0.38).rgb().string(),
    placeholder: color(white).alpha(0.54).rgb().string(),
    backdrop: color(black).alpha(0.5).rgb().string(),
    notification: pinkA100,
    disclaimerTitle: white,
    settingSectionHeader: grey76,
    headerBackground: "#393939",
    tabIcon: white,
    listItemBorder: "#121212",
    raisedCardGradient: ["#0e7cbe", "#004d8c"],
    opinionInitialsGradient: ["rgb(143,12,17)", "rgb(115,8,12)"],
    profileTextInputBorder: headerGrey,
    registrationText: white,
    meterBgColor: grey50,
    meterText: nightRider,
    wallGradient: ["#12121200", "#121212"],
    registrationText: darkmodewhite,
    darkmodeBlueText,
  },
};

export default DarkTheme;
