import color from "color";
import {
  black,
  white,
  pinkA400,
  nightRider,
  matterhorn,
  dimGray,
  grey400,
  grey300,
  greyBg,
  yellowWarning,
  darkGrey,
  titleText,
  linkBlue,
  errorText,
} from "./colors";
import configureFonts from "@styles/fonts";

const DefaultTheme = {
  dark: false,
  roundness: 4,
  colors: {
    primary: "#0072BC",
    accent: "#919191",
    background: white,
    surface: white,
    error: errorText,
    text: black,
    secondaryText: nightRider,
    whiteText: white,
    onBackground: black,
    backButton: black,
    hyperLinks: linkBlue,
    hyperLinkStyle: "none",
    onSurface: black,
    loader: "#0072BC", //Note:for now making this same as primary.
    adBox: white,
    lightBackground: greyBg,
    line: grey400,
    lineLight: grey300,
    sectionArticle: dimGray,
    publishedDate: matterhorn,
    cardBg: matterhorn,
    articleTimeStamp: black,
    navNormal: matterhorn,
    navFocused: nightRider,
    sectionTitle: nightRider,
    warning: yellowWarning,
    disabled: color(black).alpha(0.26).rgb().string(),
    placeholder: color(black).alpha(0.54).rgb().string(),
    backdrop: color(black).alpha(0.5).rgb().string(),
    notification: pinkA400,
    disclaimerTitle: matterhorn,
    settingSectionHeader: dimGray,
    headerBackground: white,
    tabIcon: "#919191",
    listItemBorder: color(black).alpha(0.26).rgb().string(),
    raisedCardGradient: ["#0e7cbe", "#004d8c"],
    opinionInitialsGradient: ["rgb(143,12,17)", "rgb(115,8,12)"],
    profileTextInputBorder: "rgba(194,194,194,0.5)",
    registrationText: darkGrey,
    registrationSubtitle: titleText,
    meterBgColor: darkGrey,
    meterText: white,
    wallGradient: ["#ffffff8d", "#FFFFFF"],
  },
  fonts: configureFonts,
  animation: {
    scale: 1.0,
  },
};

export default DefaultTheme;
